Version 1.1
PixiEditor/PixiParser pull request #2
Opened 2021-04-22 15:51 UTC by CPKreuz

2021-04-22 18:16 UTC, flabbet requested changes
typos

2021-04-22 18:16 UTC, flabbet commented on src/PixiParser/Parser/PixiParser.Deserialize.cs
> +                int layerLenght = BitConverter.ToInt32(span.Slice(pos, 4));
Length, not lenght

2021-04-22 18:16 UTC, flabbet commented on src/PixiParser/Parser/PixiParser.Deserialize.cs
> +                if (layerLenght == 0)
Same here

2021-04-22 18:35 UTC, flabbet commented
And could you please write PR description?

2021-04-22 19:52 UTC, flabbet reviewed
I don't know exactly how MessagePack, so I trust you tested it properly. Does it preserve backward compatibility?

2021-04-22 20:46 UTC, CPKreuz commented
> I don't know exactly how MessagePack, so I trust you tested it properly. Does it preserve backward compatibility? 

As far as I tested it yes

2021-04-23 12:17 UTC, flabbet approved these changes

2021-04-24 17:47 UTC, Equbuxu approved these changes
seems fine to me

2021-04-24 19:41 UTC, merged