Use Stream instead of Span<byte> for deserializing
PixiEditor/PixiParser pull request #3
Opened 2021-05-01 15:00 UTC by CPKreuz

2021-05-12 16:16 UTC, flabbet reviewed
So basically, you reverse your changes? I mean you used byte[] before and changed to Span<byte>

2021-05-12 18:06 UTC, CPKreuz commented
> So basically, you reverse your changes? I mean you used byte[] before and changed to Span

Well, first I used Span<byte> incorrectly, than I used it correctly but that introduced a bug, now I don't use it and it seems to work

2021-05-12 18:52 UTC, flabbet requested changes
Bug: Create a new layer without any pixels, save the file, open recent, select the file: crash.

Also bump package version

2021-05-21 16:18 UTC, flabbet commented
Everything works now, but one of the solution files has syntax errors. Also, bump package version.
![image](https://user-images.githubusercontent.com/25402427/119168165-e7972080-ba60-11eb-89fe-c6ee85b77018.png)

2021-05-22 06:39 UTC, flabbet requested changes

2021-05-22 06:39 UTC, flabbet commented on src/PixiParser/Helpers.cs
> +using System.Drawing;
The parser should use primitives, such as a List of bytes. PixiEditor doesn't even use System.Drawing.Color, but System.Windows.Media.Color. But it's not cross-platform, so just use bytes instead

2021-05-23 11:54 UTC, flabbet approved these changes

2021-05-23 13:03 UTC, merged