Implemented groups
PixiEditor/PixiParser pull request #4
Opened 2021-06-03 20:17 UTC by flabbet

Implemented `SerializableGuidStructureItem` (group), an array of them in document and added LayerGuid to `SerializableLayer`

2021-06-04 22:45 UTC, CPKreuz requested changes
Write tests

2021-06-06 08:58 UTC, flabbet commented
I updated the parser test, since I just added a data class, there is nothing more to test

2021-06-11 19:53 UTC, CPKreuz requested changes
I think you can remove SerializableAttribute from SerializableDocument, SerializableGuidStructureItem and SerializableLayer

2021-06-12 22:09 UTC, CPKreuz approved these changes

2021-06-13 08:15 UTC, merged